Context
Predict next-day rain by training classification models on the target variable RainTomorrow.

Content
This dataset contains about 10 years of daily weather observations from many locations across Australia.

RainTomorrow is the target variable to predict. It means -- did it rain the next day, Yes or No? This column is Yes if the rain for that day was 1mm or more.


In [ ]:
import numpy as np #impor libry
import pandas as pd

#Import the Dataset

In [ ]:
dataset = pd.read_csv('weatherAUS.csv')
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values # filtering req col
Y = dataset.iloc[:,-1].values # slicing the string -1 is from the last
print(X)


[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


#**Looking** into NA values in the dataset

In [ ]:
print(Y) # correct

['No' 'No' 'No' ... 'No' 'No' nan]


In [ ]:
Y = Y.reshape(-1,1) # converting 1D list into 2D


In [ ]:
from sklearn.impute import SimpleImputer # modeling with sklearn
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent') # mostfrq replaces na values with the most repeated value
X = imputer.fit_transform(X)
Y= imputer.fit_transform(Y)

In [ ]:
print(X)


[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [ ]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


#Encoding the Dataset

> Indented block



In [ ]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder() # as the dataset is small we go with label encdr
X[:,0] = le1.fit_transform(X[:,0]) # perform labelencoder() on the 0th col of x
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4]) # perform labelencoder() on the 4th col of x
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6]) # perform labelencoder() on the 6th col of x
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7]) # perform labelencoder() on the 7th col of x
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])# perform labelencoder() on the last col of x
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])# perform labelencoder() on the last and only col of y




In [ ]:
print(X)



[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [ ]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


#**Feature** scaling (to keep in range for plotting)

In [ ]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)


In [ ]:
print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


#**Splitting** Dataset into Training set and Test set


In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)


In [ ]:

print(X_train)

[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [ ]:
print(Y_train)

[[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


#Training Model

In [ ]:

from sklearn.ensemble import RandomForestClassifier # classifctn bcs the answer rq is yes or no
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)


ValueError: Unknown label type: 'unknown'

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create an instance of RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0)

# Ensure Y_train is a 1D array
Y_train = Y_train.ravel()

# Fit the classifier using X_train and Y_train
classifier.fit(X_train, Y_train)


In [ ]:
print(Y_train.dtype)

object


In [ ]:
print(Y_train.ndim)

1


In [ ]:
Y_train = Y_train.astype('int')

In [ ]:
classifier.fit(X_train, Y_train)

RandomForestClassifier(random_state=0)

In [ ]:

classifier.score(X_train,Y_train)

0.9999312525780283

In [ ]:

y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:155: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:

print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [ ]:
print(Y_test)

['Yes' 'Yes' 'No' ... 'Yes' 'No' 'No']


In [ ]:

y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [ ]:

df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [ ]:

print(dataframe)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No               Yes
4                    No                No
...                 ...               ...
29087                No               Yes
29088                No                No
29089               Yes                No
29090                No                No
29091                No                No

[29092 rows x 2 columns]


#Calculating Accuracy


In [ ]:

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8521930427608965

this model is 85% accurate that it would rain in Aussie tomorrow .

In [ ]:
dataset.to_csv('prediction.csv')